---
title: "Project Draft"
author: "Nischal Bhandari"
date: "06/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load packages

```{r load-packages, message=FALSE}
library(tidyverse) 
library(skimr)
library(datasauRus)
library(dplyr)
```

### Load data

```{r load-data, message = FALSE}
heart <- read_csv("data/heart.csv")
```


Ex. 1. 

### Understanding our dataset

There are `r ncol(heart)` variables and `r nrow(heart)` observations in our dataset. 

We will print out the summary of our dataset. 

```{r}
heart %>%
  skim_without_charts()
```


Ex. 2

We will plot to visualize the relationship between `age` and `resting blood pressure` of a patient with a heart disease faceted by gender. 

```{r}
ggplot(heart, mapping = aes(x = age, y = trestbps), color = sex)+
  geom_point()+
  facet_wrap(.~sex)+
  labs(
  x = "Age/years", 
  y = "Resting Blood Pressure",
  title = "Resting Blood Pressure among patients of different ages",
  subtitle = "by their gender"
)


```

